# Intelligent Customer Analytics Platform

## Phase 1: Data Understanding

### 1. Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

### 2. Load Dataset

In [3]:
df = pd.read_csv("../data/raw/online_retail_II.csv", encoding="ISO-8859-1")

### 3. Dataset Shape

In [4]:
df.shape

(1067371, 8)

### 4. Preview Dataset

In [5]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
df.sample(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
942858,572655,22699,ROSES REGENCY TEACUP AND SAUCER,6,2011-10-25 12:20:00,2.95,16708.0,United Kingdom
912738,C570274,22423,REGENCY CAKESTAND 3 TIER,-6,2011-10-10 10:52:00,10.95,13113.0,United Kingdom
877968,567673,22244,3 HOOK HANGER MAGIC GARDEN,1,2011-09-21 15:43:00,4.13,NaN,United Kingdom
806318,561507,23209,LUNCH BAG DOILEY PATTERN,10,2011-07-27 14:21:00,1.65,12397.0,Belgium
288450,517454,84836,ZINC METAL HEART DECORATION,2,2010-07-29 11:22:00,2.51,NaN,United Kingdom
46576,493704,22267,EASTER DECORATION EGG BUNNY,3,2010-01-05 14:12:00,1.25,13610.0,United Kingdom
731900,554937,21755,LOVE BUILDING BLOCK WORD,2,2011-05-27 13:32:00,5.95,15402.0,United Kingdom
333637,521973,22396,MAGNETS PACK OF 4 RETRO PHOTO,2,2010-09-09 19:46:00,1.25,17366.0,United Kingdom
216105,510364,47599B,BLUE PARTY BAGS,39,2010-05-28 16:36:00,2.10,17364.0,United Kingdom
188251,507258,22107,PIZZA PLATE IN BOX,4,2010-05-07 12:09:00,3.75,15382.0,United Kingdom

### 5. Data Types and Structure

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

### 6. Summary Statistics

In [8]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [9]:
df.describe(include="object")

,Invoice,StockCode,Description,InvoiceDate,Country
count,1067371,1067371,1062989,1067371,1067371
unique,53628,5305,5698,47635,43
top,537434,85123A,WHITE HANGING HEART T-LIGHT HOLDER,2010-12-06 16:57:00,United Kingdom
freq,1350,5829,5918,1350,981330

### 7. Missing Values Analysis

In [10]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

### 8. Duplicate Records

In [11]:
df.duplicated().sum()

np.int64(34335)

### 9. Unique Values

In [12]:
for col in df.columns:
    print(col, df[col].nunique())

Invoice 53628
StockCode 5305
Description 5698
Quantity 1057
InvoiceDate 47635
Price 2807
Customer ID 5942
Country 43

### 10. Memory Usag

In [13]:
df.memory_usage(deep=True)

Index               132
Invoice        58724905
StockCode      57757750
Description    80585729
Quantity        8538968
InvoiceDate    72581228
Price           8538968
Customer ID     8538968
Country        66618497
dtype: int64