In [27]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [28]:
from src.data.pipeline import DataPipeline

In [29]:
pipeline = DataPipeline()

clean_df = pipeline.run()

============================================================
LOADING DATASET
============================================================
Rows Loaded    : 1,067,371
Columns Loaded : 8
============================================================


============================================================
DATA VALIDATION REPORT
============================================================
✓ Required Columns : PASSED

Missing Values
Description      4382
Customer ID    243007
dtype: int64

Duplicate Rows : 34,335

Negative Quantity : 22,950
Negative Price    : 5

Data Types
Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object
============================================================
Validation Completed
============================================================


============================================================
STARTING DATA CLEANING
============================================================

Duplicate Rows Found : 34,335
Duplicate Rows Removed

c:\Users\bhard\Intelligent Customer Analytics Platform\src\data\cleaner.py:168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[DATE_COLUMN] = pd.to_datetime(df[DATE_COLUMN])

InvoiceDate converted to datetime.

Removed Missing Description : 4,275
Removed Missing Customer ID : 230,876
Removed Invalid Price Rows : 70

Cancelled Transactions : 18,390

Renamed columns to canonical schema: {'Invoice': 'InvoiceNo', 'Price': 'UnitPrice', 'Customer ID': 'CustomerID'}
Created Revenue column.
Created time-based features (Year, Month, MonthName, Day, DayName, Hour, Quarter, DayOfWeek, Week, IsWeekend, TimeOfDay).

Cleaning Completed Successfully.
============================================================

Canonical dataset saved successfully.
C:\Users\bhard\Intelligent Customer Analytics Platform\data\processed\final_cleaned_dataset.csv.gz

Compressed Dataset Size : 14.27 MB


============================================================
CLEANING SUMMARY
============================================================
Original Rows       : 1,067,371
Final Rows          : 797,815
Rows Removed        : 269,556
============================================================

In [30]:
clean_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsCancelled,Revenue,...,Month,MonthName,Day,DayName,Hour,Quarter,DayOfWeek,Week,IsWeekend,TimeOfDay
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,83.400002,...,12,December,1,Tuesday,7,4,1,49,False,Morning
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.000000,...,12,December,1,Tuesday,7,4,1,49,False,Morning
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.000000,...,12,December,1,Tuesday,7,4,1,49,False,Morning
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,100.800003,...,12,December,1,Tuesday,7,4,1,49,False,Morning
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,30.000000,...,12,December,1,Tuesday,7,4,1,49,False,Morning

In [31]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 797815 entries, 0 to 797814
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    797815 non-null  object
 1   StockCode    797815 non-null  object
 2   Description  797815 non-null  object
 3   Quantity     797815 non-null  int32
 4   InvoiceDate  797815 non-null  datetime64[ns]
 5   UnitPrice    797815 non-null  float32
 6   CustomerID   797815 non-null  float64
 7   Country      797815 non-null  category
 8   IsCancelled  797815 non-null  bool
 9   Revenue      797815 non-null  float32
 10  Year         797815 non-null  int16
 11  Month        797815 non-null  int8
 12  MonthName    797815 non-null  category
 13  Day          797815 non-null  int8
 14  DayName      797815 non-null  category
 15  Hour         797815 non-null  int8
 16  Quarter      797815 non-null  int8
 17  DayOfWeek    797815 non-null  int8
 18  Week         797815 non-null  int8
 19  IsWeekend    797815 non-null  bool
 20  TimeOfDay    797815 non-null  category
dtypes: bool(2), category(4), datetime64[ns](1), float32(2), float64(1), int16(1), int32(1), int8(6), object(3)
memory usage: 50.2+ MB

In [32]:
clean_df.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsCancelled,Revenue,...,Month,MonthName,Day,DayName,Hour,Quarter,DayOfWeek,Week,IsWeekend,TimeOfDay
count,797815,797815,797815,797815.000000,797815,797815.000000,797815.000000,797815,797815,797815.000000,...,797815.000000,797815,797815.000000,797815,797815.000000,797815.000000,797815.000000,797815.000000,797815,797815
unique,44870,4646,5299,NaN,NaN,NaN,NaN,41,2,NaN,...,NaN,12,NaN,7,NaN,NaN,NaN,NaN,2,4
top,576339,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom,False,NaN,...,NaN,November,NaN,Thursday,NaN,NaN,NaN,NaN,False,Afternoon
freq,542,5156,5149,NaN,NaN,NaN,NaN,716069,779425,NaN,...,NaN,124295,NaN,160456,NaN,NaN,NaN,NaN,666207,520033
mean,NaN,NaN,NaN,12.585594,2011-01-02 13:15:39.345813504,3.703057,15313.157440,NaN,NaN,20.418257,...,7.411384,NaN,15.387526,NaN,12.800976,2.795003,2.632767,30.102329,NaN,NaN
min,NaN,NaN,NaN,-80995.000000,2009-12-01 07:45:00,0.001000,12346.000000,NaN,NaN,-168469.593750,...,1.000000,NaN,1.000000,NaN,6.000000,1.000000,0.000000,1.000000,NaN,NaN
25%,NaN,NaN,NaN,2.000000,2010-07-02 09:47:00,1.250000,13964.000000,NaN,NaN,4.350000,...,5.000000,NaN,8.000000,NaN,11.000000,2.000000,1.000000,18.000000,NaN,NaN
50%,NaN,NaN,NaN,5.000000,2010-12-02 12:33:00,1.950000,15228.000000,NaN,NaN,11.700000,...,8.000000,NaN,15.000000,NaN,13.000000,3.000000,2.000000,33.000000,NaN,NaN
75%,NaN,NaN,NaN,12.000000,2011-07-31 15:50:00,3.750000,16789.000000,NaN,NaN,19.500000,...,10.000000,NaN,23.000000,NaN,14.000000,4.000000,4.000000,44.000000,NaN,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN,NaN,168469.593750,...,12.000000,NaN,31.000000,NaN,21.000000,4.000000,6.000000,52.000000,NaN,NaN
std,NaN,NaN,NaN,191.163061,NaN,71.395668,1696.437628,NaN,NaN,313.532501,...,3.424469,NaN,8.658267,NaN,2.306712,1.132428,1.944577,14.848352,NaN,NaN